language: go

go:
  - 1.2
  - 1.3
  - tip

install:
  - mv $HOME/gopath/src/github.com/citrusleaf $HOME/gopath/src/github.com/aerospike
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get code.google.com/p/go.tools/cmd/cover
  - wget -O aerospike-server.tgz http://aerospike.com/download/server/latest/artifact/tgz
  - tar xvzf aerospike-server.tgz
  - cp -f .travis/aerospike.conf ./aerospike-server/share/etc
  - cd aerospike-server
  - mkdir instance1
  - mkdir instance2
  - ./bin/aerospike init --home instance1 --instance 1 --service-port 3000
  - ./bin/aerospike init --home instance2 --instance 2 --service-port 3010
  - cd instance1
  - sudo ./bin/aerospike start
  - cd ../..
  - pwd
  - sleep 30
  # dump keep server log for debugging
  - sudo tail -n 1000 aerospike-server/instance1/var/log/aerospike.log

script:
  # build all tools
  - find tools -name "*.go" -type f -exec go -- build {} ';'
  # build all examples
  - find examples -type f -exec go -- build {} ';'
  # run tests in single instance mode
  - ginkgo -cover -r -race -keepGoing -succinct -randomizeSuites
  # run tests in multiple instance mode
  - cd aerospike-server/instance1
  - sudo ./bin/aerospike restart
  - cd ../instance2
  - sudo ./bin/aerospike start
  - cd ../..
  # make sure the instances are up and clean
  - sleep 30
  - ginkgo -cover -r -race -keepGoing -succinct -randomizeSuites
